# This file was generated by GoReleaser. DO NOT EDIT.
cask "boilerplate-compose" do
  desc ""
  homepage ""
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boilerplate-compose"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.2.0/boilerplate-compose_1.2.0_darwin_amd64.tar.gz"
      sha256 "7c278b12afe90252f20e843f99c22045529d522144205fd2bff9c6e56df17a5d"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.2.0/boilerplate-compose_1.2.0_darwin_arm64.tar.gz"
      sha256 "6221603a30f7d5998feb5eb77bc1ac1848bf99aa2bb76aee80727c9d710c7dd5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.2.0/boilerplate-compose_1.2.0_linux_amd64.tar.gz"
      sha256 "20a4544640d9ad85ffda13a8dfdcca23a59b8733a61eccb0260efc9adaf63348"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.2.0/boilerplate-compose_1.2.0_linux_arm64.tar.gz"
      sha256 "4317712ff2a20b2d3e68a8dd6a1ab7bc9bb4168d7585b26cd614e2b2bb3d540e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boilerplate-compose"]
    end
  end

  # No zap stanza required
end
