# This file was generated by GoReleaser. DO NOT EDIT.
cask "boilerplate-compose" do
  desc ""
  homepage ""
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boilerplate-compose"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.4.0/boilerplate-compose_1.4.0_darwin_amd64.tar.gz"
      sha256 "670253ca6a83cee51d7742a9694b6b92bf3a555b93d8526e5e95b1cbd4c67c47"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.4.0/boilerplate-compose_1.4.0_darwin_arm64.tar.gz"
      sha256 "722a921dd7cb1eafaf3dd394adc0a1bd8666ae747984b547a92734f5ae107063"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.4.0/boilerplate-compose_1.4.0_linux_amd64.tar.gz"
      sha256 "27a17553e510dff2ff15232ca113948ab2f876437a010b30b9db415456f179cd"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.4.0/boilerplate-compose_1.4.0_linux_arm64.tar.gz"
      sha256 "a3662c99602fa5a0184ea76bd84c7d5b5a948734f760438dcc28eb24af594aa6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boilerplate-compose"]
    end
  end

  # No zap stanza required
end
