# This file was generated by GoReleaser. DO NOT EDIT.
cask "boilerplate-compose" do
  desc ""
  homepage ""
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boilerplate-compose"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.3.0/boilerplate-compose_1.3.0_darwin_amd64.tar.gz"
      sha256 "9f90a6597e179f1a465cc7f1246e09a4873978ff74815c875f60faef3dc226d5"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.3.0/boilerplate-compose_1.3.0_darwin_arm64.tar.gz"
      sha256 "536116dfefe9c1074543a2240fba76646b71c9aa24b82dc0b3d4dd4ca05e3a74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.3.0/boilerplate-compose_1.3.0_linux_amd64.tar.gz"
      sha256 "28f64e804b4c68e74444dd0edd813bb87722fec837ff0eb56b0262db02b3b6d0"
    end
    on_arm do
      url "https://github.com/staticaland/boilerplate-compose/releases/download/v1.3.0/boilerplate-compose_1.3.0_linux_arm64.tar.gz"
      sha256 "cbd7aa25da7d0828237a94fa6bfefa81bbaa1c337ea174fd3df04fe63e461fcb"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boilerplate-compose"]
    end
  end

  # No zap stanza required
end
