name: Homebrew Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  brew-install:
    name: Install via Homebrew
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Add Homebrew to PATH (Linux)
        if: runner.os == 'Linux'
        run: echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"

      - name: Show brew version
        run: brew --version

      - name: Tap repository
        run: brew tap staticaland/boilerplate-compose https://github.com/staticaland/boilerplate-compose

      - name: Install cask
        run: brew install --cask boilerplate-compose

      - name: Verify binary is available
        run: |
          which boilerplate-compose
          boilerplate-compose -h || true

